### ISSUE TITLE
Implement Accessibility Guidelines for Open Data Platform (ODP)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [datopian/portal-moei#6]
# Description

When I want to to enhance the platform's inclusivity, I want to implement the the ODP with accessibility (inclusiveness) in mind as in the [design guide](https://docs.google.com/document/d/19c2Hs-8Y6Q1IW7fD5XflkQPl7USVW4Wm2q-6GyRZr_A/edit) and the universal accessibility guidelines (we currently use at Datopian), so I can ensure that the Open Data Platform (ODP) is accessible to all users, regardless of their physical abilities.

**_Note: ensure that all implementation is done with accessibility in mind._**

# Acceptance Criteria
* [ ] Examine the client's design guide to extract accessibility criteria relevant to the Open Data Platform.
* [ ] Apply accessibility as stated in the style guide
* [ ] Apply universal accessibility guidelines (used by Datopian) to enhance the ODP's accessibility features.
* [ ] Test the platform using the universal accessibility guidelines to ensure compliance.
* [ ] Test the platform using the client's style guide to ensure compliance.

# Tasks
* [ ] Apply accessibility to the pages of the ODP
* [ ] Apply the universal accessibility guidelines to the pages of the ODP
* [ ] Test the accessibility of the ODP using both the universal and the client's own design guidelines.
